"""初始結構：SLOS V1.4 鎖定總規格

Revision ID: d1d53d4e9785
Revises: 
Create Date: 2026-09-10 21:59:00.064616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import slos.types  # 自訂金額型別，autogenerate 會用到


# revision identifiers, used by Alembic.
revision: str = 'd1d53d4e9785'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by', sa.String(length=80), nullable=False),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reopened_by', sa.String(length=80), nullable=False),
    sa.Column('reopen_reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('object_type', sa.String(length=40), nullable=False),
    sa.Column('object_id', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('warning', sa.Text(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_no', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('national_id', sa.String(length=40), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('bank_account', sa.String(length=60), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_no')
    )
    op.create_table('reconciliation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.String(length=24), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('statement_ref', sa.String(length=120), nullable=False),
    sa.Column('statement_amount', slos.types.MoneyText(length=32), nullable=True),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matched_by', sa.String(length=80), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_no', sa.String(length=40), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('funding_source', sa.String(length=16), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_no')
    )
    op.create_table('contract_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('face_amount', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('term_days', sa.Integer(), nullable=False),
    sa.Column('rate_type', sa.String(length=16), nullable=False),
    sa.Column('rate_value', slos.types.RateText(length=32), nullable=False),
    sa.Column('rate_unit', sa.String(length=16), nullable=False),
    sa.Column('interest_method', sa.String(length=16), nullable=False),
    sa.Column('day_count_calendar', sa.String(length=16), nullable=False),
    sa.Column('period_flat_amount', slos.types.MoneyText(length=32), nullable=True),
    sa.Column('sticky_interest', sa.Boolean(), nullable=False),
    sa.Column('rounding_mode', sa.String(length=24), nullable=False),
    sa.Column('fee_rule', sa.Text(), nullable=False),
    sa.Column('penalty_rule', sa.Text(), nullable=False),
    sa.Column('late_interest_rule', sa.Text(), nullable=False),
    sa.Column('allocation_override', sa.Text(), nullable=False),
    sa.Column('fee_amount', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('penalty_amount', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=False),
    sa.Column('contract_ref', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'version_no', name='uq_contract_case_version')
    )
    op.create_table('external_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('ref_type', sa.String(length=24), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('evidence_type', sa.String(length=24), nullable=False),
    sa.Column('evidence_ref', sa.String(length=120), nullable=False),
    sa.Column('amount', slos.types.MoneyText(length=32), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('verified', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_no', sa.String(length=40), nullable=False),
    sa.Column('ledger_code', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('txn_type', sa.String(length=24), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.Column('reverses_entry_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['reverses_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_no'),
    sa.UniqueConstraint('ledger_code', 'idempotency_key', name='uq_ledger_idempotency')
    )
    op.create_table('settlement_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('quote_no', sa.String(length=40), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.Column('principal', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('interest', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('fee', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('penalty', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('total', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_no')
    )
    op.create_table('adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('adjust_type', sa.String(length=32), nullable=False),
    sa.Column('amount', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=80), nullable=False),
    sa.Column('legal_review_required', sa.Boolean(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('amount', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('contract_version_id', sa.Integer(), nullable=True),
    sa.Column('flag', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disbursements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('contract_version_id', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('amount', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('evidence_ref', sa.String(length=120), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('recon_status', sa.String(length=16), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_disbursement_idem')
    )
    op.create_table('extensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('from_contract_version_id', sa.Integer(), nullable=False),
    sa.Column('to_contract_version_id', sa.Integer(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('new_term_days', sa.Integer(), nullable=False),
    sa.Column('new_maturity_date', sa.Date(), nullable=False),
    sa.Column('capitalize_interest', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['from_contract_version_id'], ['contract_versions.id'], ),
    sa.ForeignKeyConstraint(['to_contract_version_id'], ['contract_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=8), nullable=False),
    sa.Column('debit', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('credit', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('subledger_bucket', sa.String(length=16), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('amount', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('evidence_ref', sa.String(length=120), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('recon_status', sa.String(length=16), nullable=False),
    sa.Column('payer_designation', sa.Text(), nullable=False),
    sa.Column('is_recovery', sa.Boolean(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_receipt_idem')
    )
    op.create_table('receivable_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('contract_version_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('trigger_event', sa.String(length=32), nullable=False),
    sa.Column('entry_cutoff_id', sa.Integer(), nullable=False),
    sa.Column('principal_outstanding', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('interest_contract', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('interest_enforceable', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('interest_received', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('interest_due', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('fee_due', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('penalty_due', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('total_due', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('overdue_days', sa.Integer(), nullable=False),
    sa.Column('flags', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['contract_version_id'], ['contract_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writeoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('amount', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=80), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=16), nullable=False),
    sa.Column('amount', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('rule_code', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('residual', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['settlement_quotes.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suspense_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('amount', slos.types.MoneyText(length=32), nullable=False),
    sa.Column('reason', sa.String(length=24), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=False),
    sa.Column('cleared_date', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suspense_entries')
    op.drop_table('settlements')
    op.drop_table('allocations')
    op.drop_table('writeoffs')
    op.drop_table('receivable_snapshots')
    op.drop_table('receipts')
    op.drop_table('journal_lines')
    op.drop_table('extensions')
    op.drop_table('disbursements')
    op.drop_table('compliance_flags')
    op.drop_table('cash_movements')
    op.drop_table('adjustments')
    op.drop_table('settlement_quotes')
    op.drop_table('journal_entries')
    op.drop_table('external_evidence')
    op.drop_table('contract_versions')
    op.drop_table('cases')
    op.drop_table('settings')
    op.drop_table('reconciliation_items')
    op.drop_table('customers')
    op.drop_table('audit_log')
    op.drop_table('accounting_periods')
    # ### end Alembic commands ###
